# Generated by Django 4.1.7 on 2023-05-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_data_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="data/")),
            ],
        ),
        migrations.RemoveField(
            model_name="data",
            name="file",
        ),
        migrations.AddField(
            model_name="data",
            name="files",
            field=models.ManyToManyField(to="core.file"),
        ),
    ]
