# Generated by Django 4.1.7 on 2023-05-16 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_file_file_mime_type_file_file_name_file_file_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
