# Generated by Django 4.1.7 on 2023-05-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_file_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="files",
            field=models.ManyToManyField(blank=True, to="core.file"),
        ),
    ]
